language: php
sudo: false
dist: trusty

jobs:
  fast_finish: true
  allow_failures:
    - php: "hhvm"
  include:
    - php: "5.3"
      dist: precise
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "7.4snapshot"
    - php: "nightly"
    - php: "hhvm"

install:
  - composer install

script:
 - vendor/bin/phpunit --coverage-text
